// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbPMF74sHaZQqaCmvPgBMUh-eehj45504',
    appId: '1:206550312586:web:882d974b9eae4a6389ef73',
    messagingSenderId: '206550312586',
    projectId: 'mobile-app-47791',
    authDomain: 'mobile-app-47791.firebaseapp.com',
    databaseURL: 'https://mobile-app-47791-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-app-47791.firebasestorage.app',
    measurementId: 'G-YZKLWWKK0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR4-gBfAITyLEHxbR7DQB05t69SG6V-z0',
    appId: '1:206550312586:android:05a9f54690f3404589ef73',
    messagingSenderId: '206550312586',
    projectId: 'mobile-app-47791',
    databaseURL: 'https://mobile-app-47791-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-app-47791.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr0ZKIse2ej6euS2-nYr7d4VvfmSa30jc',
    appId: '1:206550312586:ios:7fe6236edfee6dec89ef73',
    messagingSenderId: '206550312586',
    projectId: 'mobile-app-47791',
    databaseURL: 'https://mobile-app-47791-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-app-47791.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr0ZKIse2ej6euS2-nYr7d4VvfmSa30jc',
    appId: '1:206550312586:ios:7fe6236edfee6dec89ef73',
    messagingSenderId: '206550312586',
    projectId: 'mobile-app-47791',
    databaseURL: 'https://mobile-app-47791-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-app-47791.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbPMF74sHaZQqaCmvPgBMUh-eehj45504',
    appId: '1:206550312586:web:d09234a47b5a441789ef73',
    messagingSenderId: '206550312586',
    projectId: 'mobile-app-47791',
    authDomain: 'mobile-app-47791.firebaseapp.com',
    databaseURL: 'https://mobile-app-47791-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-app-47791.firebasestorage.app',
    measurementId: 'G-5L2BC6PQKY',
  );
}
